What's the CustomizedTools
--------------------------

CustomizedTools contain a series of tools which can help you analysing and solving question quickly, it contains:

* *JarClassSearcher:* search a class belong to which jar file in a defined folder

** User Case: './doc/uc/jarClassSearcher.asciidoc'

* *FileSearcher:* search file from a folder, even the file is packaged in jar, war, ear

link:CustomizedTools/doc/uc/fileSearcher.asciidoc[User Case]

* *FileChangeMonitor:* monitor to a defined folder, can record any change of this folder's change

link:CustomizedTools/doc/uc/fileChangeMonitor.asciidoc[User Case]

* *DBConnectionTester:* test database connection

link:CustomizedTools/doc/uc/dbConnectionTester.asciidoc[User Case]

* *JMSConnectionTester:* test jms server connection

link:CustomizedTools/doc/uc/jmsConnectionTester.asciidoc[User Case]

* *SmartAnalyser:* can automatic analysing JBoss log, JBoss configuration file, GC log, heap dump, thread dump

link:CustomizedTools/doc/uc/smartAnalyser.asciidoc[User Case]

